// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

type DeleteTodo struct {
	TodoID string `json:"todoId"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
}

type UpdateTodo struct {
	TodoID string `json:"todoID"`
	Text   string `json:"text"`
}
